"""This submodule Contains Custom Exceptions for the :code:`py_auth_micro` framework"""

class AlreadyExists(Exception):
    """An Exception to indicate a given Object already exists and can't be created again"""
    pass
